---
- name: Converge

  hosts: all

  vars:
    snapclient_host: snapcast.local

  tasks:
    - name: "Include role"
      include_role:
        name: "{{ lookup('env', 'PWD') | regex_replace('^(/.+/)', '') }}"
